# Generated by Django 4.0.2 on 2022-02-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentData',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('DepartmentName', models.CharField(max_length=50)),
                ('DateOfJoining', models.DateField()),
                ('PhotoName', models.CharField(max_length=100)),
            ],
        ),
    ]
